---
# tasks file for STRATUM
- name: Login to OpenShift
  register: oc_login
  shell: "$(which oc) login -u {{ OC_USERNAME }} -p {{ OC_PASSSWORD }} {{ OC_HOST }}"  
#############################################################
- name: Load cp image
  register: loadCpImage
  shell: "podman load -i /root/Stratum/stratum_cp.tar"
- name: Tag cp Image
  register: tag_db  
  shell: podman tag harbor.bfs.openwave.com/stratum-qe-pipeline/stratum_cp {{ REGISTRY }}/stratum_cp:3.2  
- name: Push DB image
  register: push_db
  shell: podman push {{ REGISTRY }}/stratum_cp:3.2

- name: Load ems image
  register: loadCpImage
  shell: "podman load -i /root/Stratum/stratum_ems.tar"
- name: Tag ems Image
  register: tag_db  
  shell: podman tag harbor.bfs.openwave.com/stratum-qe-pipeline/stratum_ems {{ REGISTRY }}/stratum_ems:3.2  
- name: Push DB image
  register: push_db
  shell: podman push {{ REGISTRY }}/stratum_cp:3.2

- name: Load fe image
  register: loadCpImage
  shell: "podman load -i /root/Stratum/stratum_fe.tar"
- name: Tag fe Image
  register: tag_db  
  shell: podman tag harbor.bfs.openwave.com/stratum-qe-pipeline/stratum_fe {{ REGISTRY }}/stratum_fe:3.2  
- name: Push DB image
  register: push_db
  shell: podman push {{ REGISTRY }}/stratum_fe:3.2
#############################################################
- name: Run the HEAT template
  register: runTheHeatForStratum
  shell: helm install --timeout 900s --version 3.2.0 --values /root/Stratum/charts/values.yaml region1 /root/Stratum/charts/ --debug -n enea-udr 
- name: Wait untill all pods are "Running"
  register: check_running_status
  until: check_running_status.stdout == "0"
  retries: 100
  delay: 60
  changed_when: False
  shell: "oc get pods -o wide -n enea-udr | awk {'print $3'} | grep -v 'Running' | wc -l"
- name: Wait until all pods are Ready
  register: check_ready_status
  until: check_ready_status.stdout == "0"
  retries: 100
  delay: 60
  changed_when: False
  shell: "oc get pods -o wide -n enea-udr | awk {'print $2'} | grep -v '1/1' | wc -l"
  