---
# tasks file for STRATUM
- name: Login to OpenShift
  register: oc_login
  shell: "$(which oc) login -u {{ OC_USERNAME }} -p {{ OC_PASSSWORD }} {{ OC_HOST }}"  
#############################################################
- name: Find tar files
  find:
    paths: /root/stratum329
    file_type: file
    patterns: "*.tar"
  register: files_matched
- name: Loop through the tar files and load them
  shell: |
    imageName=$(podman load -i {{ item.path }} | awk -F/ '{print $3}')
    podman tag harbor.bfs.openwave.com/stratum-qe-pipeline/$imageName {{ REGISTRY }}/$imageName
    podman push {{ REGISTRY }}/$imageName
  loop: "{{ files_matched.files }}"
#############################################################
- name: Run the HEAT template
  register: runTheHeatForStratum
  shell: |
    sed -i "s/namespace:.*/namespace: {{ NAMESPACE }}/g" /root/stratum329/stratum/values.yaml
    helm uninstall region1 -n enea-udr
    oc get pvc -nenea-udr | awk '{print "oc delete pvc "$1" -nenea-udr"}' | sh
    helm install --timeout 900s --version 3.2.9 --values /root/stratum329/stratum/values.yaml region1 /root/stratum329/stratum/ --debug -n {{ NAMESPACE }}
- name: Wait until some pods are "Running"
  register: check_running_status
  until: check_running_status.stdout != "0"
  retries: 100
  delay: 60
  changed_when: False
  shell: "oc get pods -o wide -n {{ NAMESPACE }} | grep stratum | awk {'print $3'} | grep 'Running' | wc -l"
- name: Wait until all pods are "Running"
  register: check_running_status
  until: check_running_status.stdout == "0"
  retries: 100
  delay: 60
  changed_when: False
  shell: "oc get pods -o wide -n {{ NAMESPACE }} | grep stratum | awk {'print $3'} | grep -v 'Running' | wc -l"
- name: Wait until all pods are Ready
  register: check_ready_status
  until: check_ready_status.stdout == "0"
  retries: 100
  delay: 60
  changed_when: False
  shell: "oc get pods -o wide -n {{ NAMESPACE }} | tail -n +2 | awk {'print $2'} | grep -v '1/1' | wc -l"
#############################################################
- name: Load schema
  shell: |
    oc exec -it -n{{ NAMESPACE }} region1-stratum-ild-0 -- ldapadd -D cn=root -w secret -H ldap://localhost:3389/ -f /opt/opwv/sdmce/SystemActivePath/schema/dseroot.ldif
    oc exec -it -n{{ NAMESPACE }} region1-stratum-ild-0 -- ldapadd -D cn=root -w secret -H ldap://localhost:3389/ -f /opt/opwv/sdmce/SystemActivePath/schema/schema.ldif
    oc exec -it -n{{ NAMESPACE }} region1-stratum-ild-0 -- ldapadd -D cn=root -w secret -H ldap://localhost:3389/ -f /opt/opwv/notification.ldif  


